### ISSUE TITLE
Set a conversion value instead get it from conf

### ISSUE THREAD

**Issue by lbcd** [meinfernbus/GoogleBundle#6]
Hello,

Is there a way to set a adword/conversion value instead get it from analytics.yml ?

    google:
        adwords:
            conversions:
                account_create:
                    id:    111111
                    label: accountCreateLabel
                    value: 0
                    remarketing: false
                checkout_thanks:
                    id:    222222
                    label: checkoutThanksLabel
                    value: 0           <===== I would like to set this value dynamically
                    remarketing: false

Thank you

**Comment by mente** [comment]
If it's still relevant to you - there's no way to provide value dynamically. But PRs are welcome! :)
